// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jompajmaucltulvndves.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbXBham1hdWNsdHVsdm5kdmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzk0MDEsImV4cCI6MjA3NDkxNTQwMX0.xTikWaumeqPBWLLj8cbnGxsEL-K5ldxdS1TVA4ZZrOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});